    <tr>
        <th>Id</th>
        <th>Vacancy</th>
        <th>Department</th>
        <th>Lang</th>
        <th>Department</th>
    </tr>
    <?foreach($this->rows as $key => $element):
    if($this->filter) {
        $vacancy = preg_replace("#($this->filter)#iu", "<strong style='color:#F68620'>$1</strong>", $element['vacancy']);
    } else {
        $vacancy = $element['vacancy'];
    }
    ?>
    <tr>
        <td><?=$element['id']?></td>
        <td><?=$vacancy?></td>
        <td><?=$element['description']?></td>
        <td><?=$element['lang']?></td>
        <td><?=$element['title']?></td>
    </tr>
    <?endforeach;?>
