<h1 id="wq">filter of some data</h1>

<div id="filterWrapper">
    <div class="fl" style="margin: 0 7px 0 0;">Just select or type something:</div>
    <div class="clr"></div>
    <form method="post" action="/user/edit_profile/47712/submit" onsubmit="return sendForm();">
        <select class="fl" name="department" id="department" onchange="sendForm();">
            <option value="" >Please select</option>
        <?foreach($this->deprows as $key => $element):?>
            <option value="<?=$element['id']?>"><?=$element['title']?></option>
        <?endforeach;?>
        </select>
        <input class="fl" type="text" name="vacancy" id="vacancy" >
        <select class="fl" name="lang" id="lang" onchange="sendForm();">
            <option value="" >Select language</option>
            <option value="en" >English</option>
            <option value="ru" >Русский</option>
            <option value="sp" >Español</option>
        </select>

        <input class="fl" type="submit" value="filter" >
    </form>
</div>
<div class="clr"></div>

<table id="table" cellspacing="0" cellpadding="5">
    <tr>
        <th>Id</th>
        <th>Vacancy</th>
        <th>Department</th>
        <th>Lang</th>
        <th>Department</th>
    </tr>
    <?foreach($this->rows as $key => $element):?>
    <tr>
        <td><?=$element['id']?></td>
        <td><?=$element['vacancy']?></td>
        <td><?=$element['description']?></td>
        <td><?=$element['lang']?></td>
        <td><?=$element['title']?></td>
    </tr>
    <?endforeach;?>
</table>

<script type="text/javascript">
    function sendForm() {
        jQuery.ajax({
            url : '/filter/ajaxfilter',
            data : {
                department : $('#department').val(),
                vacancy : $('#vacancy').val(),
                lang : $('#lang').val()
            },
            type : 'POST',
            async: false,
            beforeSend: function () {
                jQuery('#table').html('<div style="text-align:center;"><img src="/img/loading.gif"></div>');
            },      
            success: function(data) {
                jQuery('#table').html(data);
    
            }
        });
        return false;
    }
</script>