<form id="addForm" method="post" action="/filter/add/submit">
    <label for="title">Title</label>
    <input type="text" name="title" value="" id="title"/>
    
    <div class="clr" style="height:5px;"></div>
    
    <label for="description">Description</label>
    <textarea name="description" id="description"></textarea>
    
    <div class="clr" style="height:5px;"></div>

    <label for="language">Language</label>
    <select id="language" name="language">
        <option value="en">English</option>
        <option value="ru">Русский</option>
        <option value="sp">Español</option>
        <option value="fr">Français</option>
        <option value="sw">Svensk</option>
    </select>
    
    <div class="clr" style="height:5px;"></div>

    <label for="parentId">Parent Vacancy</label>
    <select id="parentId" name="parentId">
        <?foreach ($vacancies as $key => $vac) {
           ?>
            <option value="<? echo $vac->getId() ?>"><? echo $vac->getTitle() ?></option>
           <? 
        }?>
    </select>    
    
    <div class="clr" style="height:5px;"></div>

    <label for="departmentId">Department</label>
    <select id="departmentId" name="departmentId">
        <?foreach ($departments as $key => $dep) {
           ?>
            <option value="<? echo $dep->getId() ?>"><? echo $dep->getDepartment() ?></option>
           <? 
        }?>
    </select>    
    
    <div class="clr" style="height:5px;"></div>
     
    <input type="submit" name="submit" value="Add me" id="submit"/>
</form>