<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 <?/* <script type="text/javascript" src="http://yandex.st/jquery/1.5.1/jquery.min.js"></script>*/?>
  <script type="text/javascript" src="/jquery.min.js"></script>
  <link rel="stylesheet" href="/base.css" type="text/css" media="all" />
  <title>Just a filter</title>
</head>
<body>

<div style="margin: 0 auto; width:800px;">
<?php echo $this->layout()->content; ?>
</div>

<div style="clear:both;"></div>
</body>
</html>